source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/GE-GAO-ZHAO/TALComponentTest-Spec.git'

use_frameworks!

platform :ios, '8.0'

target 'TestModule_Example' do
  pod 'TestModule', :path => '../'
end
